services:
  db:
    platform: linux/amd64
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  dashboard:
    platform: linux/amd64
    image: rub21/osm-sandbox-dashboard:v17
    env_file:
      - ./.env
    build:
      context: images/dashboard/
      dockerfile: Dockerfile
    volumes:
      - ./images/dashboard/src:/app
      # - /Users/samirkoirala/Desktop/k3s.osmsandbox.naxadev.com.yml:/app/kubeconfig.yml:ro
      - ./images/dashboard/src/kubeconfig.yml:/root/.kube/config:ro

    ports:
      - "8000:8000"
    networks:
      - default
      - k3d-mycluster
    depends_on:
      - db
    # working_dir: /app

networks:
  k3d-mycluster:
    external: true